-- create category table
CREATE TABLE category (
    category_id integer generated by default as identity,
    category_name VARCHAR(20) NOT NULL
);

-- create address table
CREATE TABLE address (
    address_id integer generated by default as identity,
    address_1 VARCHAR(20) NOT NULL,
    address_2 VARCHAR(20) NOT NULL
);

-- create member table
CREATE TABLE members (
account VARCHAR(50) primary key,
password VARCHAR(20) NOT NULL,
address VARCHAR(50) NOT NULL,
category_id_1 integer NULL,
category_id_2 integer NULL,
category_id_3 integer NULL,
address_id_1 integer NULL,
address_id_2 integer NULL,
address_id_3 integer NULL,
member_type integer NOT NULL
);
